project_id = "jjcrfaznizffenslgsxp"

[functions.ai-search]
verify_jwt = false

[functions.ai-categorize]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-copilot]
verify_jwt = false
